services:
  rag-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-api-service
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    env_file:
      - .env
    networks:
      - roblox-rag-net

  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scraper-service
    command: python scraper/main.py
    depends_on:
      - qdrant
    env_file:
      - .env
    networks:
      - roblox-rag-net

  qdrant:
    image: qdrant/qdrant:latest
    container_name: vector-db-service
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    env_file:
      - .env
    networks:
      - roblox-rag-net

  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-server-service
    command: python mcp_server/main.py
    ports:
      - "8001:8001"
    depends_on:
      - rag-api
    env_file:
      - .env
    networks:
      - roblox-rag-net

volumes:
  qdrant_data:


networks:
  roblox-rag-net:
    driver: bridge
