services:
  mcp-server-local:
    build:
      context: .
      dockerfile: src/mcp_server/Dockerfile.local
    ports:
      - "8000:8000"
    volumes:
      # Mount the qdrant_data and src directories, preserving the .venv from the build.
      - ./qdrant_data:/app/qdrant_data
      - ./src:/app/src
      # Use named volumes for caches to persist them on the host
      - ./local-build-caches/poetry_cache:/opt/poetry_cache
      - ./local-build-caches/apt_cache:/var/cache/apt
    environment:
      - POETRY_CACHE_DIR=/opt/poetry_cache
