[tool.poetry]
name = "roblox-api-rag"
version = "0.1.0"
description = "Roblox API RAG Agent Knowledge Base"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.111.0"
uvicorn = {extras = ["standard"], version = "^0.30.1"}
qdrant-client = "^1.9.0"
llama-index = "^0.10.50"
apscheduler = "^4.1.0"
scrapy = "^2.11.2"
pydantic = "^2.7.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"